--CREATE ENTITY TYPE (1: FOR INSTITUTION 2: INSTITUTION ADMIN 3: TEACHER 4: STUDENT)
CREATE TABLE TG_ENTITY_TYPE(ID INT NOT NULL, NAME VARCHAR(100) NOT NULL, DESCRIPTION VARCHAR(500),
PRIMARY KEY (ID));

-- CREATE ADDRESS TABLE
CREATE TABLE TG_ADDRESS(ID INT NOT NULL, STATE VARCHAR(100), CITY VARCHAR(100), ADDRESS VARCHAR(100),
PIN_CODE INT,LAST_UPDATE TIMESTAMP NOT NULL, PRIMARY KEY(ID));

--CREATE INSTITUTION
CREATE TABLE TG_INSTITUTION (ID INT NOT NULL, NAME VARCHAR(200) NOT NULL, EMAIL VARCHAR(100) NOT NULL,
CONTACT INTEGER NOT NULL, TG_ADDRESS_ID INT, LOGO VARCHAR(100),
LATITUDE REAL CHECK (LATITUDE IS NULL OR (LATITUDE >= -90 AND LATITUDE <= 90)),
LONGITUDE REAL CHECK (LONGITUDE IS NULL OR (LONGITUDE >= -180 AND LONGITUDE <= 180)),LAST_UPDATE TIMESTAMP,
 IS_ACTIVE BIT, PRIMARY KEY (ID), FOREIGN KEY(TG_ADDRESS_ID) REFERENCES TG_ADDRESS(ID));

-- CREATE INSTITUTION ADMIN TABLE
CREATE TABLE TG_INSTITUTION_ADMIN(ID INT NOT NULL, NAME VARCHAR(100) NOT NULL, PIC VARCHAR(100),
TG_INSTITUTION_ID INT, TG_ADDRESS_ID INT, LAST_UPDATE TIMESTAMP, IS_ACTIVE BIT NOT NULL DEFAULT '0',
PRIMARY KEY (ID), FOREIGN KEY(TG_INSTITUTION_ID) REFERENCES TG_INSTITUTION(ID),
FOREIGN KEY(TG_ADDRESS_ID) REFERENCES TG_ADDRESS(ID));

--CREATE INSTITUTION TEACHER
CREATE TABLE TG_INSTITUTION_TEACHER(ID INT NOT NULL, NAME VARCHAR(100) NOT NULL, PIC VARCHAR(100), DOB DATE,
TG_ADDRESS_ID INT, TG_INSTITUTION_ID INT, LAST_UPDATE TIMESTAMP, IS_ACTIVE BIT NOT NULL DEFAULT '0',
PRIMARY KEY (ID), FOREIGN KEY(TG_INSTITUTION_ID) REFERENCES TG_INSTITUTION(ID),
FOREIGN KEY(TG_ADDRESS_ID) REFERENCES TG_ADDRESS(ID));

--CREATE INSTITUTION STUDENT
CREATE TABLE TG_INSTITUTION_STUDENTS(ID INT NOT NULL, NAME VARCHAR(100) NOT NULL, PIC VARCHAR(100), DOB DATE,
TG_ADDRESS_ID INT, TG_INSTITUTION_ID INT, LAST_UPDATE TIMESTAMP, IS_ACTIVE BIT NOT NULL DEFAULT '0',
PRIMARY KEY (ID), FOREIGN KEY(TG_INSTITUTION_ID) REFERENCES TG_INSTITUTION(ID),
FOREIGN KEY(TG_ADDRESS_ID) REFERENCES TG_ADDRESS(ID));

--CREATE LOGIN DETAILS
CREATE TABLE TG_LOGIN_DETAILS(ID INT NOT NULL, EMAIL VARCHAR(100), CONTACT INT,PASSWORD VARCHAR(100),
OTP INT, TG_ENTITY_TYPE_ID INT, LAST_UPDATE TIMESTAMP, PRIMARY KEY (ID),
FOREIGN KEY(TG_ENTITY_TYPE_ID) REFERENCES TG_ENTITY_TYPE(ID));

--CREATE CATEGORY TABLE
CREATE TABLE TG_SHORTHAND_CATEGORY(ID INT NOT NULL, NAME VARCHAR(100) NOT NULL, CREATED_BY INT,
 TG_INSTITUTION_ID INT, LAST_UPDATE TIMESTAMP, IS_ACTIVE BIT NOT NULL DEFAULT '1', PRIMARY KEY (ID),
FOREIGN KEY(TG_INSTITUTION_ID) REFERENCES TG_INSTITUTION(ID), FOREIGN KEY(CREATED_BY)
  REFERENCES TG_INSTITUTION_TEACHER(ID));

-- CREATE SHORTHAND WORD
CREATE TABLE TG_SHORTHAND_WORD(ID INT NOT NULL, ENGLISH_WORD VARCHAR(100) NOT NULL,
SHORT_HAND_WORD BYTEA, CREATED_BY INT, CATEGORY_ID INT,  LAST_UPDATE TIMESTAMP, IS_ACTIVE BIT NOT NULL DEFAULT '1', PRIMARY KEY (ID),
FOREIGN KEY(CREATED_BY) REFERENCES TG_INSTITUTION_TEACHER(ID), FOREIGN KEY(CATEGORY_ID) REFERENCES TG_SHORTHAND_CATEGORY(ID));
